# Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

reviews:
  profile: assertive
  commit_status: false
  auto_review:
    enabled: true
